name: adding-artifacts

on: 
  workflow_call:
    inputs:
      artifact_name:
        description: Storing the artifact name
        required: true
        default: jar-file
        type: string

jobs:
  adding-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: sunil716/assignment-hello-spring
          ref: artifacts-store
      - name: Downloading the Artifact(JAR File)
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact_name }}
      - name: Listing all files
        run: |
          git init 
          ls -al
          git branch
      - name: Commit files
        run: |
          git config --global user.email ${{ secrets.GH_EMAIL }}
          git config --global user.name ${{ secrets.GH_USERNAME }}
          git add .
          git commit -a -m "Adding the Artifact File(JAR File)"
          git branch
          git remote -v
          git push origin artifacts-store
      