# Name of the workflow
name: adding-artifacts

# This is a reusable workflow which can be triggered by other workflows
on: 
  workflow_call:
    # Inputs that needs to be passed while calling the workflow
    inputs:
      artifact-name:
        description: Storing the artifact name
        required: true
        default: jar-file
        type: string

# Environment variables
env:
  email: sunilgajula333@gmail.com
  username: sunil716

# Jobs in this workflow
jobs:
  # A job to upload the artifact into artifact-store branch
  adding-artifacts:
    # Runs on latest version of ubuntu
    runs-on: ubuntu-latest
    #  Steps involved in the job
    steps:
      - name: Checking out the artifacts-store branch in the current repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: artifacts-store
      - name: Downloading the Artifact(JAR File)
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Listing all files
        run: |
          ls -al
      - name: Commit files
        run: |
          git init 
          git config --global user.email $email
          git config --global user.name $username
          git add .
          git commit -a -m "Adding the Artifact File(JAR File)"
          git branch
          git remote -v
          git push origin artifacts-store
      