name : Task-1 in assignment - Build, test, package the code and uploading artifacts to different branch

on : workflow_dispatch

jobs :
  build-test-package : 
    runs-on : ubuntu-latest
    steps :
      - name : Getting the application code
        uses : actions/checkout@v3
      # - name : Setup Maven Action
      #   uses : s4u/setup-maven-action@v1.7.0
      - name : Set up JDK 17
        uses : actions/setup-java@v3
        with :
          java-version : '17'
          distribution : 'temurin'
      - name : Build Stage
        run : mvn clean compile
      - name : Testing Stage
        run : mvn test
      - name : Packaging the code
        run : mvn package
      