name : Build, test, package

on : 
  workflow_dispatch:
    inputs:
      workflow_02:
        description: 'Adding Artifacts will be  triggered'
        required: true
        default: 'adding-artifacts'

      workflow2_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':$username'

      workflow2_repo_github:
        description: 'repo-name'
        required: true
        default: ':assignment-hello-spring' 
  push:

env:
  email: sunilgajula333@gmail.com
  username: sunil716
  pat: ${{ secrets.PAT }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs :
  build-test-package : 
    runs-on : ubuntu-latest
    steps :
      - name : Getting the application code
        uses : actions/checkout@v3
      - name : Set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
      - name : Build Stage
        run : mvn clean compile
      - name : Testing Stage
        run : mvn test
      - name : Packaging the code
        run : mvn package
      - name : Uploading the Artifact(JAR File)
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/:userName/:repoName/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PAT }} \
          --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'