name : Build, test, package

on : [workflow_dispatch, push]

env:
  email: sunilgajula333@gmail.com
  username: sunil716
  pat: ${{ secrets.PAT }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs :
  build-test-package : 
    runs-on : ubuntu-latest
    steps :
      - name : Getting the application code
        uses : actions/checkout@v3
      - name : Set up JDK 11
        uses : actions/setup-java@v3
        with :
          java-version : '11'
          distribution : 'temurin'
      - name : Build Stage
        run : mvn clean compile
      - name : Testing Stage
        run : mvn test
      - name : Packaging the code
        run : mvn package
      - name : Uploading the Artifact(JAR File)
        uses: actions/upload-artifact@v3
        with:
          name: jar-file
          path: target/*.jar

  adding-artifacts:
    needs: build-test-package
    uses: ./.github/workflows/add-artifacts.yml